var express = require('express');
var cors = require('cors');

testAPIRouter=require('./routes/testApi');
containerLISTRouter=require('./routes/container list');
imageLISTRouter=require('./routes/image list');
volumeLISTRouter=require('./routes/volume list');
versionRouter=require('./routes/version');
createContainer=require('./routes/create container');
pullImage=require('./routes/pull image');
detailImg=require('./routes/detailsImg');
Networkls=require('./routes/Network');
NetworkInspect=require('./routes/InspectNet');
cmdl = require('./routes/commandlines');
NetworkDownload = require('./routes/downs');
push=require('./routes/push');
console.log(process.env.USERPROFILE);
var app = express();
var PORT=9000;
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cors())
app.use('/testapi',testAPIRouter);
app.use('/container-ls',containerLISTRouter);
app.use('/image-ls',imageLISTRouter);
app.use('/volume-ls',volumeLISTRouter);
app.use('/version',versionRouter);
app.use('/createContainers',createContainer);
app.use('/shareContainers',push);
app.use('/PullImg*',pullImage);
app.use('/DetailsImg*',detailImg);
app.use('/Network',Networkls);
app.use('/Network-*',NetworkInspect);
app.use('/download-*',NetworkDownload);
app.use('/cmd?*',cmdl);
app.listen(PORT,() => console.log(`Server is running on port ${PORT}`));